### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by EphraimBane** [devanhurst/ktane_voice#16]
I'm pretty sure I installed everything right, but when I try to run Charlie I get this error:
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        from charlie.rb:2:in `require'
        from charlie.rb:2:in `<main>'
```

**Comment by Gabgab2003** [comment]
I think i have the same error: ```C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `r
equire': cannot load such file -- ffi_c (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:6:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        from charlie.rb:2:in `require'
        from charlie.rb:2:in `<main>'```

**Comment by Gabgab2003** [comment]
<code>C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `r
equire': cannot load such file -- ffi_c (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:6:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        from charlie.rb:2:in `require'
        from charlie.rb:2:in `<main>'`</code>

**Comment by downloadpizza** [comment]
I have the same Error on windows 7:
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `r
equire': cannot load such file -- ffi_c (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:6:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ffi-1.9.10-x64-mingw32/lib/f
fi.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/pocketsphinx-ruby-f2
f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        from charlie.rb:2:in `require'
        from charlie.rb:2:in `<main>'
```
