### ISSUE TITLE
Yes, another damn Windows 10 issue.

### ISSUE THREAD

**Issue by ggtylerr** [devanhurst/ktane_voice#18]
I doubt this will make any difference seeing as how this is 2 years old and there's already a lot of Windows issues, but I figured it might be worth mentioning this.
http://prntscr.com/kvmtwj
Getting this error message whenever I try to load it up. Built Pocketsphinx and Sphinxbase using Visual Studio 2017 and downloaded espeak normally.

NOTE: Might be an issue with me installing Pocketsphinx and Sphinxbase. Installation on their included readme file didn't really specify anything else other than to build. If this is the case, I'd be happy to follow any directions I have to take in order to properly install them.

Edit: Non-image format of error message
```Traceback (most recent call last):
        8: from charlie.rb:2:in `<main>'
        7: from charlie.rb:2:in `require'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)
```

**Comment by devanhurst** [comment]
ffi is a dependency that gets installed using the `bundle install` command. Did that complete successfully when run from the project root directory?
