### ISSUE TITLE
Unable to install on windows 10

### ISSUE THREAD

**Issue by ghost** [devanhurst/ktane_voice#19]
Look at me, another Windows 10 error
SO, basically, i had a lot of trouble trying to get Rbenv and pocketsphinx to work, but now i am stuck
when i try to run the bundle command, i get

> Traceback (most recent call last):
        2: from C:/Ruby25-x64/bin/bundle:23:in `<main>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

And when i try to run charlie.rb, i get

> Traceback (most recent call last):
        2: from charlie.rb:1:in `<main>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

Somebody please help, i have been trying to get this work for like 2 hours and i am starting to lose hope

Why couldnt this have been an easier time, just like a single .exe file i could run
Keep in mind i am a literal noob at this kind of stuff
I feel like i am so close, i can almost get it running

**Comment by devanhurst** [comment]
Okay, I'm finally going to chime in. This wasn't designed for Windows 10, plain and simple. Getting ruby to run on Windows is a real pain. You'll have a better time trying to get this to work if you install a small Ubuntu virtual machine specifically for development with Ruby. Did you try using this tool to install Ruby? https://rubyinstaller.org/

Anyway, your bundle install command is failing. The Gemfile.lock was bundled with bundler version 1.11.2. Maybe try installing that specific version of bundler and try again. `gem install bundler:1.11.2`

**Comment by ghost** [comment]
Update:
I have managed to get the bundler working, but when I try to do the command "ruby charlie.rb" I get another, lovely error
Beware, it's a long one
Also, I have the latest version of Ruby (2.6.0) and have managed to get rbenv working. just this one issue left (i think) and then I can do it

> Traceback (most recent call last):
        7: from charlie.rb:2:in `<main>'
        6: from charlie.rb:2:in `require'
        5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:4:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:4:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
        8: from charlie.rb:2:in `<main>'
        7: from charlie.rb:2:in `require'
        6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)

Thank you so much for the help, I really do appreciate it
Edit: I did find other programs similar to this, but they don't have all the modules or features of Charlie, so this is the only option for me really
Edit 2: tried installing Ubuntu, it just flat out didn't install at all. just got stuck, not even the clock worked

**Comment by devanhurst** [comment]
Was that error resolved by #20 ?
