### ISSUE TITLE
Its me, again

### ISSUE THREAD

**Issue by ghost** [devanhurst/ktane_voice#20]
edit nvm im stupid and didnt put enough ram into the vm oops

**Comment by devanhurst** [comment]
For everyone else, which issue did this solve? What point are you at now?

**Comment by ghost** [comment]
nevermind ubuntu hates me and wont install, sorry for the confusion and me being stupid
The error follows below

> Traceback (most recent call last): 7: from charlie.rb:2:in `<main>'         6: from charlie.rb:2:in `require' 5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require' 3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require' 1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:4:in `<top (required)>' C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:4:in `require': cannot load such file -- 2.6/ffi_c (LoadError) 8: from charlie.rb:2:in `<main>'         7: from charlie.rb:2:in `require' 6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require' 4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `<top (required)>'         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:1:in `require' 2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:3:in `<top (required)>'         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `rescue in <top (required)>' C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.9.10-x64-mingw32/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)

EDIT: UBUNTU IS TRYING TO INSTALL I DONT KNOW WHY THIS THING HATES ME AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Edit 2: ok I give up, my laptop isn't powerful enough to get Ubuntu running, and I still haven't got this set up on windows.
I'm gonna stop no and leave you guys alone
Cya
Thanks for the help
Bye

**Comment by ghost** [comment]
ok hi im back just saying that i reinstalled everything, and it still didnt work. so, unless you are some super windows genius, please, for your own sanity, dont try to set this up on windows

**Comment by uwuplant** [comment]
agreed

**Comment by GhoustPrivate** [comment]
has anyone managed to make this work on windows 10? When i try to run the bundle command or charlie.rb, it just closes the window immediately. Is there something i haven't installed properly?

**Comment by ddugovic** [comment]
Dude, I spent a day trying to get this working on Windows and didn't get anywhere.  I'd recommend trying to do it on Linux.

**Comment by YukiRainee** [comment]
sorry to necro this back from the grave but did anyone get this working on Linux or Windows yet?
