### ISSUE TITLE
Failed to run on OSX El Capitan (10.11.3)

### ISSUE THREAD

**Issue by xcession** [devanhurst/ktane_voice#4]
I did `gem install bundler` then run `bundle` to install all required gems.

```
$ bundle
Using espeak-ruby 1.0.2
Using ffi 1.9.10
Using ordinator 1.0.1
Using require_all 1.3.3
Using bundler 1.11.2
Using pocketsphinx-ruby 0.3.0
Bundle complete!
```

I also follow the install instruction from https://github.com/watsonbox/pocketsphinx-ruby

```
$ brew tap watsonbox/cmu-sphinx
$ brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase
$ brew install --HEAD watsonbox/cmu-sphinx/cmu-pocketsphinx
```

When I try to run `charlie.rb` I got this error message.

```
$ ruby charlie.rb
/usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libpocketsphinx': dlopen(libpocketsphinx, 5): image not found. (LoadError)
Could not open library 'libpocketsphinx.dylib': dlopen(libpocketsphinx.dylib, 5): image not found
    from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:5:in `<module:Pocketsphinx>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:3:in `<module:API>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:2:in `<module:Pocketsphinx>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx.rb:8:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from charlie.rb:1:in `<main>'
```

**Comment by apepindev** [comment]
What's your `gem env`?

**Comment by xcession** [comment]
Here...

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/xcession/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/xcession/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.3.0
     - /Users/xcession/.gem/ruby/2.3.0
     - /usr/local/Cellar/ruby/2.3.0/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/CrossPack-AVR/bin
```

**Comment by apepindev** [comment]
Try adding `/usr/local/Cellar/ruby/2.3.0/bin` to your path.

**Comment by xcession** [comment]
Added as you suggest.

```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/CrossPack-AVR/bin:/usr/local/Cellar/ruby/2.3.0/bin
```

Then...

```
$ ruby charlie.rb
/usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libpocketsphinx': dlopen(libpocketsphinx, 5): image not found. (LoadError)
Could not open library 'libpocketsphinx.dylib': dlopen(libpocketsphinx.dylib, 5): image not found
    from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
    from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:5:in `<module:Pocketsphinx>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:3:in `<module:API>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:2:in `<module:Pocketsphinx>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/pocketsphinx.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx.rb:8:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from charlie.rb:1:in `<main>'
```

**Comment by ashleypancho** [comment]
Did you `source ~/.bash_profile` in between getting pocketsphinx and `ruby charlie.rb`? 

I had a similar problem the other night, also running El Capitan. I got it mostly working but I always did a resource and I did have to uninstall and reinstall bundler a few times.

**Comment by apepindev** [comment]
Have you tested pocketsphinx using `pocketsphinx_continuous -inmic yes`?

If it works then it could mean that the pocketsphinx-ruby gem is not being able to reach the pocketsphinx library you got through Homebrew. 

It also looks like you're using Ruby through Homebrew. I'm using mine through rbenv and I didn't come across this problem.

**Comment by xcession** [comment]
Alright, after I went through uninstall and re-install everything.
I got less error message.

```
$ ruby charlie.rb
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from charlie.rb:2:in `<main>'
```

**Comment by ashleypancho** [comment]
Now just install pry. IIRC it's `$gem install pry`

**Comment by apepindev** [comment]
I had this error too. I just added `gem 'pry'` in the `GemFile` and I had no more errors.

EDIT: and run bundle, of course.

**Comment by xcession** [comment]
After install the `pry` gem.
I run `$ ruby charlie.rb` and heard the voice `My name is Charlie.`, `Let's roll.`.
Then few seconds after I got the error message about `pocketsphinx` again.

```
$ ruby charlie.rb
2016-03-14 22:26:18.209 espeak[71802:966255] 22:26:18.207 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
2016-03-14 22:26:20.025 espeak[71803:966311] 22:26:20.024 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
2016-03-14 22:26:21.484 ruby[71801:966232] 22:26:21.482 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]          [DEFLT]     [VALUE]
-agc            none        none
-agcthresh      2.0     2.000000e+00
-allphone
-allphone_ci        no      no
-alpha          0.97        9.700000e-01
-ascale         20.0        2.000000e+01
-aw         1       1
-backtrace      no      no
-beam           1e-48       1.000000e-48
-bestpath       yes     yes
-bestpathlw     9.5     9.500000e+00
-ceplen         13      13
-cmn            current     current
-cmninit        8.0     40,3,-1
-compallsen     no      no
-debug                  0
-dict                   /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase       no      no
-dither         no      no
-doublebw       no      no
-ds         1       1
-fdict
-feat           1s_c_d_dd   1s_c_d_dd
-featparams
-fillprob       1e-8        1.000000e-08
-frate          100     100
-fsg
-fsgusealtpron      yes     yes
-fsgusefiller       yes     yes
-fwdflat        yes     yes
-fwdflatbeam        1e-64       1.000000e-64
-fwdflatefwid       4       4
-fwdflatlw      8.5     8.500000e+00
-fwdflatsfwin       25      25
-fwdflatwbeam       7e-29       7.000000e-29
-fwdtree        yes     yes
-hmm                    /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us
-input_endian       little      little
-jsgf
-keyphrase
-kws
-kws_delay      10      10
-kws_plp        1e-1        1.000000e-01
-kws_threshold      1       1.000000e+00
-latsize        5000        5000
-lda
-ldadim         0       0
-lifter         0       22
-lm                 /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us.lm.bin
-lmctl
-lmname
-logbase        1.0001      1.000100e+00
-logfn
-logspec        no      no
-lowerf         133.33334   1.300000e+02
-lpbeam         1e-40       1.000000e-40
-lponlybeam     7e-29       7.000000e-29
-lw         6.5     6.500000e+00
-maxhmmpf       30000       30000
-maxwpf         -1      -1
-mdef
-mean
-mfclogdir
-min_endfr      0       0
-mixw
-mixwfloor      0.0000001   1.000000e-07
-mllr
-mmap           yes     yes
-ncep           13      13
-nfft           512     512
-nfilt          40      25
-nwpen          1.0     1.000000e+00
-pbeam          1e-48       1.000000e-48
-pip            1.0     1.000000e+00
-pl_beam        1e-10       1.000000e-10
-pl_pbeam       1e-10       1.000000e-10
-pl_pip         1.0     1.000000e+00
-pl_weight      3.0     3.000000e+00
-pl_window      5       5
-rawlogdir
-remove_dc      no      no
-remove_noise       yes     yes
-remove_silence     yes     yes
-round_filters      yes     yes
-samprate       16000       1.600000e+04
-seed           -1      -1
-sendump
-senlogdir
-senmgau
-silprob        0.005       5.000000e-03
-smoothspec     no      no
-svspec                 0-12/13-25/26-38
-tmat
-tmatfloor      0.0001      1.000000e-04
-topn           4       4
-topn_beam      0       0
-toprule
-transform      legacy      dct
-unit_area      yes     yes
-upperf         6855.4976   6.800000e+03
-uw         1.0     1.000000e+00
-vad_postspeech     50      50
-vad_prespeech      20      20
-vad_startspeech    10      10
-vad_threshold      2.0     2.000000e+00
-var
-varfloor       0.0001      1.000000e-04
-varnorm        no      no
-verbose        no      no
-warp_params
-warp_type      inverse_linear  inverse_linear
-wbeam          7e-29       7.000000e-29
-wip            0.65        6.500000e-01
-wlen           0.025625    2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(164): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(206): Reading HMM transition probability matrices: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(354): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(835): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138623 * 32 bytes (4331 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/cmudict-en-us.dict
INFO: dict.c(213): Allocated 1014 KiB for strings, 1677 KiB for phones
INFO: dict.c(336): 134522 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(353): Trying to read LM in trie binary format
INFO: ngram_search_fwdtree.c(99): 790 unique initial diphones
INFO: ngram_search_fwdtree.c(148): 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(186): Creating search tree
INFO: ngram_search_fwdtree.c(192): before: 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(326): after: max nonroot chan increased to 152144
INFO: ngram_search_fwdtree.c(339): after: 722 root, 152016 non-root channels, 53 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]          [DEFLT]     [VALUE]
-agc            none        none
-agcthresh      2.0     2.000000e+00
-allphone
-allphone_ci        no      no
-alpha          0.97        9.700000e-01
-ascale         20.0        2.000000e+01
-aw         1       1
-backtrace      no      no
-beam           1e-48       1.000000e-48
-bestpath       yes     yes
-bestpathlw     9.5     9.500000e+00
-ceplen         13      13
-cmn            current     current
-cmninit        8.0     40,3,-1
-compallsen     no      no
-debug                  0
-dict                   /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase       no      no
-dither         no      no
-doublebw       no      no
-ds         1       1
-fdict
-feat           1s_c_d_dd   1s_c_d_dd
-featparams
-fillprob       1e-8        1.000000e-08
-frate          100     100
-fsg
-fsgusealtpron      yes     yes
-fsgusefiller       yes     yes
-fwdflat        yes     yes
-fwdflatbeam        1e-64       1.000000e-64
-fwdflatefwid       4       4
-fwdflatlw      8.5     8.500000e+00
-fwdflatsfwin       25      25
-fwdflatwbeam       7e-29       7.000000e-29
-fwdtree        yes     yes
-hmm                    /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us
-input_endian       little      little
-jsgf
-keyphrase
-kws
-kws_delay      10      10
-kws_plp        1e-1        1.000000e-01
-kws_threshold      1       1.000000e+00
-latsize        5000        5000
-lda
-ldadim         0       0
-lifter         0       22
-lm                 /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us.lm.bin
-lmctl
-lmname
-logbase        1.0001      1.000100e+00
-logfn
-logspec        no      no
-lowerf         133.33334   1.300000e+02
-lpbeam         1e-40       1.000000e-40
-lponlybeam     7e-29       7.000000e-29
-lw         6.5     6.500000e+00
-maxhmmpf       30000       30000
-maxwpf         -1      -1
-mdef
-mean
-mfclogdir
-min_endfr      0       0
-mixw
-mixwfloor      0.0000001   1.000000e-07
-mllr
-mmap           yes     yes
-ncep           13      13
-nfft           512     512
-nfilt          40      25
-nwpen          1.0     1.000000e+00
-pbeam          1e-48       1.000000e-48
-pip            1.0     1.000000e+00
-pl_beam        1e-10       1.000000e-10
-pl_pbeam       1e-10       1.000000e-10
-pl_pip         1.0     1.000000e+00
-pl_weight      3.0     3.000000e+00
-pl_window      5       5
-rawlogdir
-remove_dc      no      no
-remove_noise       yes     yes
-remove_silence     yes     yes
-round_filters      yes     yes
-samprate       16000       1.600000e+04
-seed           -1      -1
-sendump
-senlogdir
-senmgau
-silprob        0.005       5.000000e-03
-smoothspec     no      no
-svspec                 0-12/13-25/26-38
-tmat
-tmatfloor      0.0001      1.000000e-04
-topn           4       4
-topn_beam      0       0
-toprule
-transform      legacy      dct
-unit_area      yes     yes
-upperf         6855.4976   6.800000e+03
-uw         1.0     1.000000e+00
-vad_postspeech     50      50
-vad_prespeech      20      20
-vad_startspeech    10      10
-vad_threshold      2.0     2.000000e+00
-var
-varfloor       0.0001      1.000000e-04
-varnorm        no      no
-verbose        no      no
-warp_params
-warp_type      inverse_linear  inverse_linear
-wbeam          7e-29       7.000000e-29
-wip            0.65        6.500000e-01
-wlen           0.025625    2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(164): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(206): Reading HMM transition probability matrices: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(354): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(835): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138623 * 32 bytes (4331 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/cmudict-en-us.dict
INFO: dict.c(213): Allocated 1014 KiB for strings, 1677 KiB for phones
INFO: dict.c(336): 134522 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/Cellar/cmu-pocketsphinx/HEAD/share/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(353): Trying to read LM in trie binary format
INFO: ngram_search_fwdtree.c(99): 790 unique initial diphones
INFO: ngram_search_fwdtree.c(148): 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(186): Creating search tree
INFO: ngram_search_fwdtree.c(192): before: 0 root, 0 non-root channels, 57 single-phone words
INFO: ngram_search_fwdtree.c(326): after: max nonroot chan increased to 152144
INFO: ngram_search_fwdtree.c(339): after: 722 root, 152016 non-root channels, 53 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
/usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:10:in `block in api_call': Decoder#unset_search failed with error code -1 (Pocketsphinx::API::Error)
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:8:in `tap'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/api/call_helpers.rb:8:in `api_call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:178:in `unset_search'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/configuration/grammar.rb:15:in `post_init_decoder'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:206:in `post_init_decoder'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:194:in `init_decoder'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/decoder.rb:30:in `initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:22:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:22:in `decoder'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:86:in `stop'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:59:in `ensure in recognize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/pocketsphinx-ruby-0.3.0/lib/pocketsphinx/speech_recognizer.rb:59:in `recognize'
    from charlie.rb:30:in `select_module'
    from charlie.rb:140:in `<main>'
```

**Comment by ashleypancho** [comment]
Take a look at issue #2, it will fix that problem.

**Comment by devanhurst** [comment]
lol Sorry about leaving Pry out of the Gemfile, everyone! :P
