### ISSUE TITLE
Missing Sphinxbase/Pocketsphinx libraries (Windows)

### ISSUE THREAD

**Issue by UmbyUmbreon** [devanhurst/ktane_voice#8]
This was previously reported in the comments of #1 but the issue was closed beforehand, and I'm experiencing the same thing.

The Windows builds of Sphinxbase, whether they are retrieved from CMU Sphinx's SourceForge page or built from source, only contain the library sphinxbase.dll. The program expects libsphinxbase.dll, libsphinxad.dll, and possibly others.

One workaround to the program expecting libsphinxbase.dll is to rename sphinxbase.dll to libsphinxbase.dll, though this doesn't help with libsphinxad.dll being missing. Not sure if simply renaming the file would make the program crash and burn, as I haven't gotten far enough to test it due to libsphinxad.dll being missing.

Here is the output, it's worth noting that this could be a pocketshpinx-ruby issue as well? I'm not too versed in Ruby so I can't honestly tell.

```
D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ffi-1.9.10-x86-mingw32/lib/
ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libsphinxbase'
 (LoadError)ied module could not be found.
.
Could not open library 'libsphinxbase.dll': The specified module could not be fo
und.
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ffi-1.9.10-x86
-mingw32/lib/ffi/library.rb:100:in `map'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ffi-1.9.10-x86
-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:5:in `<module:Sphinx
base>'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:3:in `<module:API>'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:2:in `<module:Pocket
sphinx>'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:1:in `<top (required
)>'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:6:in `require'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:6:in `<top (required)>'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
        from D:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/bundler/gems/pocket
sphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
        from charlie.rb:2:in `require'
        from charlie.rb:2:in `<main>'
```

**Comment by BrunoMoreira99** [comment]
Exactly same output as mine. I noticed that there are folders in **sphinxbase\src** named **libsphinxad** and **libsphinxbase**, I believe that's the source for the libraries?

The solution has a bunch of projects (7 if I can recall) but only **sphinxbase** project has the output in its properties for **sphinxbase.dll**.

**Comment by CarbonNeuron** [comment]
I Cant Even figure out how to install Spinx base or pocketspinx I Rlly need help :( i need more information then just Install these things

**Comment by BrunoMoreira99** [comment]
The problem is that it isn't even an installation (at least for Windows users), there is no Homebrew for Windows so we need to do this manually, which is going to take a while if we don't figure out how to get the required libraries.

**Comment by devanhurst** [comment]
@CarbonNeuron I'm on my Windows machine from time to time trying to work it out. Please be patient.

**Comment by CarbonNeuron** [comment]
Any Updates?
This Bot Looks Amazing

**Comment by Admiral-99** [comment]
Any updates?? It has been a few years

**Comment by SharpBit** [comment]
@CarbonNeuron it's been almost 3 years but if you're still wondering, you need to install gradle and java 

installation guide here: https://www.360logica.com/blog/how-to-configure-gradle-on-windows-machine/
one comment said don't use `%GRADLE_HOME%\bin` for the new Path environmental variable, so put the full path e.g. `C:\Users\CarbonNeuron\Downloads\gradle-2.8-all-or-whatever-it-was\bin`
It says to edit a Path environ var but u need to make a new one

Then you need to go to the directory of the source download for sphinx base and pocketsphinx and type `gradle build`

However, I'm still stuck on the error of this issue with 
```
C:\Users\Jason\ktane_voice>ruby charlie.rb
Traceback (most recent call last):
        12: from charlie.rb:2:in `<main>'
        11: from charlie.rb:2:in `require'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `<top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx-ruby.rb:1:in `require'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:6:in `<top (required)>'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx.rb:6:in `require'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:1:in `<top (required)>'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:2:in `<module:Pocketsphinx>'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:3:in `<module:API>'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/pocketsphinx-ruby-f2f562bdc66b/lib/pocketsphinx/api/sphinxbase.rb:5:in `<module:Sphinxbase>'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not op (LoadError)libsphinxbase': The specified module could not be found.
.
Could not open library 'libsphinxbase.dll': The specified module could not be found.
```

**Comment by SharpBit** [comment]
@devanhurst any updates on the original error?

**Comment by offensiveburrito** [comment]
> @devanhurst any updates on the original error?

Have you figured it out?

im still having trouble
